#!/bin/sh /etc/rc.common
# probe data post process start on boot
# Mon Nov  2 10:00:54 CST 2015 created by GaomingPan
#

START=98
STOP=50

start()
{
  /usr/bin/wifiSmartAc.sh 
}


restart()
{
  rst=`ps | grep wifiSmartAc | cut -d "r" -f 1`
  if [ -n "$rst" ]
   then
    kill -9 $rst
 fi
 
 /usr/bin/wifiSmartAc.sh 
 
}

stop()
{
  rst=`ps | grep wifiSmartAc | cut -d "r" -f 1`
  if [ -n "$rst" ]
   then
    kill -9 $rst
 fi
}




