#!/bin/sh
#############################################################
#
# 作 者：潘田园
# 日 期：2016-03-04
# 版 本：
#
# 脚本描述：
#	这个脚本是用于更新修改版的 wifidog 认证客户端列表；
# 即：使用户从 wifidog 上下线。
#
############################################################

. /usr/bin/accmd_common

############################################################
#
# $(1) cmd_id
# $(2) gw_ac_id
# $(3) mac_list
#
# 参数描述：
#	以上三个参数由外部调用者传进来。说明如下：
# cmd_id：字符串，命令id
# gw_ad_id: 字符串，网关id
# mac_list: MAC 字符串列表，格式为： "mac1 mac2 mac3 mac4 ..."
#
#############################################################

WDCTL=/usr/bin/wifiSmartac_update_doglist
OPTS=$3
if [ "$OPTS" == "" ]
then
   ErrorMessage $1 $2 "update client list MAC-list Param error."
   exit 1
fi

$WDCTL $OPTS &> /dev/null

if [ $? == 0 ]
then
   SuccessMessage $1 $2 "update list ok."
   exit 0
fi

ErrorMessage $1 $2 "update client list error."

exit 1


