#!/bin/sh
###############################################################
#
# 作 者：潘田园
# 日 期：2016-03-09
# 版 本：
#
# 脚本描述：
#	此脚本用于设置 MAC 地址的黑白名单，在没有 wifidog 的情况下，
# 只能设置黑名单，要设置白名单必须要有 wifidog。
#
###############################################################


###############################################################
#
# $(1) cmd_id
# $(2) gw_ac_id
# $(3) dogflag
# $(4) "b_mac1 b_mac2 b_mac3 ..."
# $(5) "w_mac1 w_mac2 w_mac3 ..."
#
###############################################################


. /usr/bin/accmd_common


BLACK_MAC="$4"
WHITE_MAC="$5"

ret=0
reta=0
retb=0

if [ $BLACK_MAC != "NULL" ]
then
    /usr/bin/accmd_update_mac_fw_tables $1 $2 $3 black "$BLACK_MAC"  > /dev/null
    reta=$?
else
    /usr/bin/accmd_update_mac_fw_tables $1 $2 $3 cancel_black  > /dev/null
    reta=$?
fi

if [ $WHITE_MAC != "NULL" ]
then
   /usr/bin/accmd_update_mac_fw_tables $1 $2 $3 white "$WHITE_MAC" > /dev/null
   retb=$?
else
   /usr/bin/accmd_update_mac_fw_tables $1 $2 $3 cancel_white > /dev/null
   retb=$?
fi

ret=$(($reta+$retb))


case $ret in
     0) SuccessMessage $1 $2 "Set white black mac list ok.";;
     *) ErrorMessage $1 $2   "Internal ERROR. Set white black mac list maybe NOT success.";;
esac


     
     
