#!/bin/sh
###############################################################################################################################
#
# description: get the settings of wireless,
#		lan,wan,reboot_info and dhcp.
#		use in OpenWrt router,based on uci
# Version: 1.0.0
# Author: TianyuanPan
#         2015-07-29
#
# Pram:  $1 cmd_id
# 	 $2 gw_ac_id
#
################################################################################################################################

. /usr/bin/accmd_common


##
# wifi info
##
int_wifi_disable=$(uci get wireless.radio0.disabled)
if [ -z "$int_wifi_disable" ]
then
  int_wifi_disable=0
fi

str_wifi_ssid=$(uci get wireless.@wifi-iface[0].ssid)

int_wifi_ssidHidden=$(uci get wireless.@wifi-iface[0].hidden)
if [ -z "$int_wifi_ssidHidden" ]
then
  int_wifi_ssidHidden=0
fi

str_wifi_encryption=$( uci get wireless.@wifi-iface[0].encryption)
str_wifi_key=$(uci get wireless.@wifi-iface[0].key)


#
# lan info
#
str_lan_ipAddress=$(uci get network.lan.ipaddr)
str_lan_ipMask=$(uci get network.lan.netmask)

#
# dhcp info
#
int_dhcp_ignore=$(uci get dhcp.lan.ignore)
if [ -z $int_dhcp_ignore ]
then
   int_dhcp_ignore=0
fi

int_dhcp_start=$(uci get dhcp.lan.start)
if [ -z $int_dhcp_start ]
then
   int_dhcp_start=100
fi

int_dhcp_limit=$(uci get dhcp.lan.limit)
if [ -z $int_dhcp_limit ]
then
   int_dhcp_limit=50
fi

str_dhcp_leaseTime=$(uci get dhcp.lan.leasetime)


#
# auto boot inifo
#
crontabs=$(cat /etc/crontabs/root|grep reboot)
if [ -z $str_sys_rebootTime ]
then
   str_sys_rebootTime=""
else
   str_sys_rebootTime="$(cat /etc/crontabs/root|grep reboot|awk '{print $2,":",$1}')"
fi

if [ -z $str_sys_rebootTime ]
then
   int_sys_autoReboot=0
else
   int_sys_autoReboot=1
fi



echo "{\"cmd_id\":\"$1\",\"gw_ac_id\":\"$2\",\"status\":true,\"info\":\"Get settings success.\",\"data\":{\"disable\":$int_wifi_disable,\"ssid\":\"$str_wifi_ssid\",\"ssidHidden\":$int_wifi_ssidHidden,\"encryption\":\"$str_wifi_encryption\",\"key\":\"$str_wifi_key\",\"ipAddress\":\"$str_lan_ipAddress\",\"ipMask\":\"$str_lan_ipMask\",\"ignore\":$int_dhcp_ignore,\"start\":$int_dhcp_start,\"limit\":$int_dhcp_limit,\"leaseTime\":\"$str_dhcp_leaseTime\",\"autoReboot\":$int_sys_autoReboot,\"rebootTime\":\"$str_sys_rebootTime\"}}"


