#!/bin/sh
###############################################################
## 此 shell 文件 执行的功能是，更新WIFI dog 里已经认证的客户端。
## 即，把已经认证的客户从列表里移除。
################################################################

# 包含一个公共的函数集文件
. /usr/bin/accmd_common

############################################
# $(1) cmd_id: string
# $(2) gw_ac_id: string
# $(3) mac_list: "mac1 mac2 mac3 ..."
#
# 这三个参数是由外部传进来的 命令ID、网关ID、MAC地址串集合
###############################################

WDCTL=/usr/bin/wifiSmartac_update_doglist
OPTS=$3
if [ "$OPTS" == "" ]
then
   ErrorMessage $1 $2 "update client list MAC-list Param error."
   exit 1
fi

$WDCTL $OPTS &> /dev/null

if [ $? == 0 ]
then
   echo "{\"gw_ac_id\":\"$2\",\"cmd_id\":\"$1\",\"status\":true,\"info\":\"update list ok.\"}"
   exit 0
fi

ErrorMessage $1 $2 "update client list error."

exit 1


