#!/bin/sh
#########################################
#
# 作 者：潘田园
# 日 期：2016-03-04
# 版 本：
#
# 脚本描述：
#	设置路由器的 DHCP 服务信息
#
##########################################


###########################################################################
# $(1): cmd_id
# $(2): gw_ac_id
# $(3): dhcp_IP_start 
# $(4): dhcp_IP_limit numbers
# $(5): dhcp_leasetime min:2m, normal:12h
# $(6): dhcp_switch, 0 OPEN dhcp, 1 CLOSE dhcp
#
# 参数说明：
#	cmd_id:          命令ID
#	gw_ac_id:        网关ID
#	dhcp_IP_start:   dhcp 的开始地址
#	dhcp_IP_limit:   dhcp 地址容量
#	dhcp_leasetime:  IP地址的租期时间， 最小 2 分钟
#	dhcp_switch:     dhcp 开关， 值为 0 开启dhcp， 值为 1 关闭 dhcp
#
###########################################################################

start=$3
limit=$4
leasetime=$5
ignore=$6


. /usr/bin/internal_common


if [ $# != 6 ];then
    ErrorMessage $1 $2 "set dhcp parameter error."
    exit 1
fi


if [ $start == "" ];then
    start=100
fi


if [ $limit == "" ];then
   limit=150
fi

if [ $leasetime == "" ];then
  leasetime=12
fi

case $ignore in
  "1")
  ignore=1
  ;;
  *)
  ignore=0
  ;;
esac

uci set dhcp.lan.start=$start
uci set dhcp.lan.limit=$limit
uci set dhcp.lan.leasetime=$leasetime
uci set dhcp.lan.ignore=$ignore
uci commit dhcp

ret=$?
if [ $ret != 0 ];then
    ErrorMessage $1 $2 "uci commit dhcp ERROR."
    exit 1
fi

RebootInterface lan
ret=$?
if [ $ret != 0 ];then
    ErrorMessage $1 $2 "reboot lan interface error."
    exit 1
fi

start=$(uci get dhcp.lan.start)
limit=$(uci get dhcp.lan.limit)
leasetime=$(uci get dhcp.lan.leasetime)
ignore=$(uci get dhcp.lan.ignore)

if [ "$ignore" == "" ]; then
      ignore=0
fi

info="Set DHCP Success."

echo "{\"cmd_id\":\"$1\",\"gw_ac_id\":\"$2\",\"status\":true,\"info\":\"$info\",\"data\":{\"start\":$start,\"limit\":$limit,\"leasetime\":\"$leasetime\",\"ignore\":$ignore}}"








